#!/bin/sh
# Export src/xapp as a WeChat mini-program ("xapp-mini") with HBuilderX's own compiler.
#
# `xcli launch mp-weixin --compile true` works on Linux but only as a dev compile into
# src/xapp/unpackage/dist/dev/mp-weixin, and `xcli publish mp-weixin` wants an appid + upload
# key. This runs the exact command and environment `xcli launch mp-weixin` spawns (captured
# from /proc on HBuilderX 5.26), in build mode, then stamps the project config.
# Output: dist/xapp/mini — open that folder in WeChat DevTools.
#
#   tools/xapp-mini/build.sh                         # production build, appid touristappid
#   APPID=wx84bd7d00a6fd626e tools/xapp-mini/build.sh   # real appid: real-device preview, wx.login
#   HBX=/path/to/HBuilderX tools/xapp-mini/build.sh
set -e
ROOT=$(cd "$(dirname "$0")/../.." && pwd)
X="$ROOT/src/xapp"
OUT="$ROOT/dist/xapp/mini"
HBX=${HBX:-}
if [ -z "$HBX" ]; then
  if [ -d /Applications/HBuilderX.app/Contents/HBuilderX/plugins/uniapp-cli-vite ]; then
    HBX=/Applications/HBuilderX.app
  else
    HBX="$HOME/HBuilderX"
  fi
fi
case "$HBX" in
  *.app) HBX_ROOT="$HBX/Contents/HBuilderX" ;;
  *) HBX_ROOT="$HBX" ;;
esac
PLUGIN="$HBX_ROOT/plugins/uniapp-cli-vite"
APPID=${APPID:-touristappid}
[ -d "$PLUGIN" ] || { echo "HBuilderX compiler not found at $PLUGIN (set HBX=)"; exit 1; }

rm -rf "$OUT"
mkdir -p "$(dirname "$OUT")"
# Deps (vue, @dcloudio/*) resolve from the plugin's node_modules, so run from there.
(cd "$PLUGIN" && env -i PATH="$HBX_ROOT/plugins/node:/usr/bin:/bin" HOME="$HOME" LD_LIBRARY_PATH="$HBX_ROOT" \
  NODE_SKIP_PLATFORM_CHECK=1 HBUILDER_EXTENSIONS_DIR="$HBX_ROOT/plugins" HX_Version=5.26 \
  NODE_ENV=production UNI_PLATFORM=mp-weixin \
  UNI_INPUT_DIR="$X" UNI_OUTPUT_DIR="$OUT" \
  HX_DEPENDENCIES_DIR="$X/unpackage/cache/uts_cache" UNI_APP_X_CACHE_DIR="$X/unpackage/cache/.mp-weixin" \
  UNI_HBUILDERX_LANGID=en UNI_CLOUD_SPACES='[]' NO_COLOR=true \
  "$HBX_ROOT/plugins/node/node" --no-warnings "$PLUGIN/node_modules/@dcloudio/vite-plugin-uni/bin/uni.js" build -p mp-weixin)

# The compiler writes a touristappid config named after manifest.json; make it this project.
node -e '
const fs = require("fs"), p = process.argv[1] + "/project.config.json";
const c = JSON.parse(fs.readFileSync(p, "utf8"));
c.appid = process.argv[2]; c.projectname = "xapp-mini";
c.description = "uni-app x port (src/xapp) exported as a WeChat mini-program — generated by tools/xapp-mini/build.sh, do not edit";
c.setting.urlCheck = false;
// Use DevTools ES6 conversion with its legacy compiler: SWC broke the minified generators
// (ReferenceError: C is not defined on startup, reproduced on M3).
Object.assign(c.setting, { es6: true, swc: false, disableSWC: true });
// DevTools packs a preview/upload; unminified, that output pushed
// the main package past WeChat 2 MB limit (2162 KB, error 80051, 2026-10-02).
Object.assign(c.setting, { minified: true, minifyWXSS: true, minifyWXML: true });
fs.writeFileSync(p, JSON.stringify(c, null, 2) + "\n");
' "$OUT" "$APPID"
echo "xapp-mini → ${OUT#$ROOT/} ($(du -sh "$OUT" | cut -f1), appid $APPID)"
