#!/bin/sh
# Export src/xapp as a WeChat mini-program ("xapp-mini") with HBuilderX's own compiler.
#
# `xcli launch mp-weixin --compile true` works on Linux but only as a dev compile into
# src/xapp/unpackage/dist/dev/mp-weixin, and `xcli publish mp-weixin` wants an appid + upload
# key. This runs the exact command and environment `xcli launch mp-weixin` spawns (captured
# from /proc on HBuilderX 5.26), in build mode, then stamps the project config.
# Output: src/xapp-mini — open that folder in WeChat DevTools.
#
#   tools/xapp-mini/build.sh                         # production build, appid touristappid
#   APPID=wx84bd7d00a6fd626e tools/xapp-mini/build.sh   # real appid: real-device preview, wx.login
#   HBX=/path/to/HBuilderX tools/xapp-mini/build.sh
set -e
ROOT=$(cd "$(dirname "$0")/../.." && pwd)
X="$ROOT/src/xapp"
OUT="$ROOT/src/xapp-mini"
HBX=${HBX:-$HOME/HBuilderX}
PLUGIN="$HBX/plugins/uniapp-cli-vite"
APPID=${APPID:-touristappid}
[ -d "$PLUGIN" ] || { echo "HBuilderX not found at $HBX (set HBX=)"; exit 1; }

rm -rf "$OUT"
# Deps (vue, @dcloudio/*) resolve from the plugin's node_modules, so run from there.
(cd "$PLUGIN" && env -i PATH="$HBX/plugins/node:/usr/bin:/bin" HOME="$HOME" LD_LIBRARY_PATH="$HBX" \
  NODE_SKIP_PLATFORM_CHECK=1 HBUILDER_EXTENSIONS_DIR="$HBX/plugins" HX_Version=5.26 \
  NODE_ENV=production UNI_PLATFORM=mp-weixin \
  UNI_INPUT_DIR="$X" UNI_OUTPUT_DIR="$OUT" \
  HX_DEPENDENCIES_DIR="$X/unpackage/cache/uts_cache" UNI_APP_X_CACHE_DIR="$X/unpackage/cache/.mp-weixin" \
  UNI_HBUILDERX_LANGID=en UNI_CLOUD_SPACES='[]' NO_COLOR=true \
  "$HBX/plugins/node/node" --no-warnings "$PLUGIN/node_modules/@dcloudio/vite-plugin-uni/bin/uni.js" build -p mp-weixin)

# The compiler writes a touristappid config named after manifest.json; make it this project.
node -e '
const fs = require("fs"), p = process.argv[1] + "/project.config.json";
const c = JSON.parse(fs.readFileSync(p, "utf8"));
c.appid = process.argv[2]; c.projectname = "xapp-mini";
c.description = "uni-app x port (src/xapp) exported as a WeChat mini-program — generated by tools/xapp-mini/build.sh, do not edit";
c.setting.urlCheck = false;
fs.writeFileSync(p, JSON.stringify(c, null, 2) + "\n");
' "$OUT" "$APPID"
echo "xapp-mini → ${OUT#$ROOT/} ($(du -sh "$OUT" | cut -f1), appid $APPID)"
