#!/usr/bin/env node
// Writes src/xapp/static/web/user-app.css — the stylesheet the xapp's web build renders with.
// It is the web user-app's stylesheet, assembled the same way: the web shell + theme tokens
// + web-overrides from src/web/user-app, and the miniapp's WXSS converted by the same rules as
// src/web/user-app/scripts/sync-css-from-miniapp.mjs (rpx ÷ 2 = px, `page{}`/`:host{}` dropped).
// The one difference is the element map: the xapp renders uni-app x's custom elements
// (<uni-view>, <uni-text>, …), not the user-app's <div>/<span>. Converted from the WXSS on
// every build rather than copied from user-app/src/mini-css, which is only as current as its
// last `npm run sync:css`.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const MINI = path.join(ROOT, 'src/mini/nano-miniapp');
const UA = path.join(ROOT, 'src/web/user-app/src');
const OUT = path.join(ROOT, 'src/xapp/static/web/user-app.css');

// Same list and order as user-app/src/main.jsx's imports (login.css is not imported there —
// the web login screen is styled by style.css).
const WXSS = [
  'pages/main/main.wxss',
  'components/toolbox/toolbox.wxss',
  'components/user-health/user-health.wxss',
  'components/health-documents/health-documents.wxss',
  'components/viva-ag-panel/viva-ag-panel.wxss',
  'components/avatar-picker/avatar-picker.wxss',
  'pages/phones/phones.wxss',
  'pages/emails/emails.wxss',
  'pages/referral/referral.wxss',
];

const ELEMENT_MAP = {
  view: 'uni-view', text: 'uni-text', image: 'uni-image', navigator: 'uni-navigator',
  'scroll-view': 'uni-scroll-view', 'rich-text': 'uni-rich-text',
};

function convert(css) {
  css = css.replace(/^@import\s+[^;]+;\s*$/gm, '');
  css = css.replace(/(^|\n)(page|:host)\s*\{[^}]*\}/g, '$1');
  css = css.replace(/(-?\d+(?:\.\d+)?)rpx/g, (_, n) => `${n / 2}px`);
  css = css.replace(/([ >+~])(view|text|image|navigator|scroll-view|rich-text)(?=[\s,{:.#\[])/g, (m, pre, el) => pre + ELEMENT_MAP[el]);
  return css;
}

const parts = [
  `/* GENERATED by tools/xapp-web/sync-css.mjs — do not edit. Regenerated on every web build. */`,
  fs.readFileSync(path.join(UA, 'theme-tokens.css'), 'utf8'),
  fs.readFileSync(path.join(UA, 'style.css'), 'utf8').replace(/^@import\s+'\.\/theme-tokens\.css';\s*$/m, ''),
  ...WXSS.map(src => `/* ── ${src} ── */\n` + convert(fs.readFileSync(path.join(MINI, src), 'utf8'))),
  // The user-app generated this from coach.wxss with view/text/image → div/span/img; map those
  // element selectors on to uni's elements like the WXSS above.
  fs.readFileSync(path.join(UA, 'coach/generated/coach.css'), 'utf8')
    .replace(/([ >+~])(div|span|img)(?=[\s,{:.#\[])/g, (m, pre, el) => pre + ({ div: 'uni-view', span: 'uni-text', img: 'uni-image' })[el]),
  fs.readFileSync(path.join(UA, 'coach/coach.css'), 'utf8'),
  fs.readFileSync(path.join(UA, 'web-overrides.css'), 'utf8'),
];
fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, parts.join('\n\n'));
console.log(`wrote ${path.relative(ROOT, OUT)} (${Math.round(fs.statSync(OUT).size / 1024)} KB)`);
