-- Issues the PRECISION LONGEVITY PRACTITIONER certification (certification_id=1)
-- to all 31 students enrolled via migration_academy_plp_enroll_students*.sql,
-- using each student's real 证书编号 from temp/PLP Student List.xlsx (not an
-- auto-generated number, since these already have an official paper cert
-- number). issue_date/expiry_date default to the certification's shared
-- cohort dates. cert_oss_key is pre-set to a deterministic key
-- (academy/cert-rendered/{certificate_number}.png) that a follow-up local
-- script renders and uploads to OSS -- keeping the key here means no
-- separate ad-hoc UPDATE against prod is needed after image generation.
-- Idempotent via ON CONFLICT (user_id, certification_id) DO NOTHING.

INSERT INTO academy_coach_certifications (user_id, certification_id, earned_at, is_manual_issue, certificate_number, issue_date, expiry_date, cert_oss_key) SELECT 'e983e7c2', 1, NOW(), TRUE, 'SCHCD012188', c.issue_date, c.validity_date, 'academy/cert-rendered/SCHCD012188.png' FROM academy_certifications c WHERE c.id = 1 ON CONFLICT (user_id, certification_id) DO NOTHING;
INSERT INTO academy_coach_certifications (user_id, certification_id, earned_at, is_manual_issue, certificate_number, issue_date, expiry_date, cert_oss_key) SELECT '217438b4', 1, NOW(), TRUE, 'SCHZJ072733', c.issue_date, c.validity_date, 'academy/cert-rendered/SCHZJ072733.png' FROM academy_certifications c WHERE c.id = 1 ON CONFLICT (user_id, certification_id) DO NOTHING;
INSERT INTO academy_coach_certifications (user_id, certification_id, earned_at, is_manual_issue, certificate_number, issue_date, expiry_date, cert_oss_key) SELECT 'f44c794a', 1, NOW(), TRUE, 'SCHBJ156623', c.issue_date, c.validity_date, 'academy/cert-rendered/SCHBJ156623.png' FROM academy_certifications c WHERE c.id = 1 ON CONFLICT (user_id, certification_id) DO NOTHING;
INSERT INTO academy_coach_certifications (user_id, certification_id, earned_at, is_manual_issue, certificate_number, issue_date, expiry_date, cert_oss_key) SELECT 'e1a4a5a5', 1, NOW(), TRUE, 'SCHSH074011', c.issue_date, c.validity_date, 'academy/cert-rendered/SCHSH074011.png' FROM academy_certifications c WHERE c.id = 1 ON CONFLICT (user_id, certification_id) DO NOTHING;
INSERT INTO academy_coach_certifications (user_id, certification_id, earned_at, is_manual_issue, certificate_number, issue_date, expiry_date, cert_oss_key) SELECT 'f6b766d1', 1, NOW(), TRUE, 'SCHSH050011', c.issue_date, c.validity_date, 'academy/cert-rendered/SCHSH050011.png' FROM academy_certifications c WHERE c.id = 1 ON CONFLICT (user_id, certification_id) DO NOTHING;
INSERT INTO academy_coach_certifications (user_id, certification_id, earned_at, is_manual_issue, certificate_number, issue_date, expiry_date, cert_oss_key) SELECT '6d20b3da', 1, NOW(), TRUE, 'SCHSH220466', c.issue_date, c.validity_date, 'academy/cert-rendered/SCHSH220466.png' FROM academy_certifications c WHERE c.id = 1 ON CONFLICT (user_id, certification_id) DO NOTHING;
INSERT INTO academy_coach_certifications (user_id, certification_id, earned_at, is_manual_issue, certificate_number, issue_date, expiry_date, cert_oss_key) SELECT 'd389f03b', 1, NOW(), TRUE, 'SCHSH187320', c.issue_date, c.validity_date, 'academy/cert-rendered/SCHSH187320.png' FROM academy_certifications c WHERE c.id = 1 ON CONFLICT (user_id, certification_id) DO NOTHING;
INSERT INTO academy_coach_certifications (user_id, certification_id, earned_at, is_manual_issue, certificate_number, issue_date, expiry_date, cert_oss_key) SELECT '2b623b60', 1, NOW(), TRUE, 'SCHHZ014987', c.issue_date, c.validity_date, 'academy/cert-rendered/SCHHZ014987.png' FROM academy_certifications c WHERE c.id = 1 ON CONFLICT (user_id, certification_id) DO NOTHING;
INSERT INTO academy_coach_certifications (user_id, certification_id, earned_at, is_manual_issue, certificate_number, issue_date, expiry_date, cert_oss_key) SELECT '0b9ef1ba', 1, NOW(), TRUE, 'SCHGZ144047', c.issue_date, c.validity_date, 'academy/cert-rendered/SCHGZ144047.png' FROM academy_certifications c WHERE c.id = 1 ON CONFLICT (user_id, certification_id) DO NOTHING;
INSERT INTO academy_coach_certifications (user_id, certification_id, earned_at, is_manual_issue, certificate_number, issue_date, expiry_date, cert_oss_key) SELECT '6656d4e8', 1, NOW(), TRUE, 'SCHHZ202310', c.issue_date, c.validity_date, 'academy/cert-rendered/SCHHZ202310.png' FROM academy_certifications c WHERE c.id = 1 ON CONFLICT (user_id, certification_id) DO NOTHING;
INSERT INTO academy_coach_certifications (user_id, certification_id, earned_at, is_manual_issue, certificate_number, issue_date, expiry_date, cert_oss_key) SELECT 'fa52ae8f', 1, NOW(), TRUE, 'SCHHLBE220011', c.issue_date, c.validity_date, 'academy/cert-rendered/SCHHLBE220011.png' FROM academy_certifications c WHERE c.id = 1 ON CONFLICT (user_id, certification_id) DO NOTHING;
INSERT INTO academy_coach_certifications (user_id, certification_id, earned_at, is_manual_issue, certificate_number, issue_date, expiry_date, cert_oss_key) SELECT '15231f7a', 1, NOW(), TRUE, 'SCHSH162340', c.issue_date, c.validity_date, 'academy/cert-rendered/SCHSH162340.png' FROM academy_certifications c WHERE c.id = 1 ON CONFLICT (user_id, certification_id) DO NOTHING;
INSERT INTO academy_coach_certifications (user_id, certification_id, earned_at, is_manual_issue, certificate_number, issue_date, expiry_date, cert_oss_key) SELECT 'eb821c10', 1, NOW(), TRUE, 'SCHSH143425', c.issue_date, c.validity_date, 'academy/cert-rendered/SCHSH143425.png' FROM academy_certifications c WHERE c.id = 1 ON CONFLICT (user_id, certification_id) DO NOTHING;
INSERT INTO academy_coach_certifications (user_id, certification_id, earned_at, is_manual_issue, certificate_number, issue_date, expiry_date, cert_oss_key) SELECT '3d96f3d8', 1, NOW(), TRUE, 'SCHHZ044122', c.issue_date, c.validity_date, 'academy/cert-rendered/SCHHZ044122.png' FROM academy_certifications c WHERE c.id = 1 ON CONFLICT (user_id, certification_id) DO NOTHING;
INSERT INTO academy_coach_certifications (user_id, certification_id, earned_at, is_manual_issue, certificate_number, issue_date, expiry_date, cert_oss_key) SELECT '641a6b10', 1, NOW(), TRUE, 'SCHSH152024', c.issue_date, c.validity_date, 'academy/cert-rendered/SCHSH152024.png' FROM academy_certifications c WHERE c.id = 1 ON CONFLICT (user_id, certification_id) DO NOTHING;
INSERT INTO academy_coach_certifications (user_id, certification_id, earned_at, is_manual_issue, certificate_number, issue_date, expiry_date, cert_oss_key) SELECT 'fce8f13a', 1, NOW(), TRUE, 'SCHSH098211', c.issue_date, c.validity_date, 'academy/cert-rendered/SCHSH098211.png' FROM academy_certifications c WHERE c.id = 1 ON CONFLICT (user_id, certification_id) DO NOTHING;
INSERT INTO academy_coach_certifications (user_id, certification_id, earned_at, is_manual_issue, certificate_number, issue_date, expiry_date, cert_oss_key) SELECT '2e62dc28', 1, NOW(), TRUE, 'SCHSH104622', c.issue_date, c.validity_date, 'academy/cert-rendered/SCHSH104622.png' FROM academy_certifications c WHERE c.id = 1 ON CONFLICT (user_id, certification_id) DO NOTHING;
INSERT INTO academy_coach_certifications (user_id, certification_id, earned_at, is_manual_issue, certificate_number, issue_date, expiry_date, cert_oss_key) SELECT 'e045248d', 1, NOW(), TRUE, 'SCHSH2100414', c.issue_date, c.validity_date, 'academy/cert-rendered/SCHSH2100414.png' FROM academy_certifications c WHERE c.id = 1 ON CONFLICT (user_id, certification_id) DO NOTHING;
INSERT INTO academy_coach_certifications (user_id, certification_id, earned_at, is_manual_issue, certificate_number, issue_date, expiry_date, cert_oss_key) SELECT '3298795e', 1, NOW(), TRUE, 'SCHSH142846', c.issue_date, c.validity_date, 'academy/cert-rendered/SCHSH142846.png' FROM academy_certifications c WHERE c.id = 1 ON CONFLICT (user_id, certification_id) DO NOTHING;
INSERT INTO academy_coach_certifications (user_id, certification_id, earned_at, is_manual_issue, certificate_number, issue_date, expiry_date, cert_oss_key) SELECT '5891fcf0', 1, NOW(), TRUE, 'SCHSH18004X', c.issue_date, c.validity_date, 'academy/cert-rendered/SCHSH18004X.png' FROM academy_certifications c WHERE c.id = 1 ON CONFLICT (user_id, certification_id) DO NOTHING;
INSERT INTO academy_coach_certifications (user_id, certification_id, earned_at, is_manual_issue, certificate_number, issue_date, expiry_date, cert_oss_key) SELECT '74a9b0c1', 1, NOW(), TRUE, 'SCHSH090024', c.issue_date, c.validity_date, 'academy/cert-rendered/SCHSH090024.png' FROM academy_certifications c WHERE c.id = 1 ON CONFLICT (user_id, certification_id) DO NOTHING;
INSERT INTO academy_coach_certifications (user_id, certification_id, earned_at, is_manual_issue, certificate_number, issue_date, expiry_date, cert_oss_key) SELECT '619cbc19', 1, NOW(), TRUE, 'SCHSH150067', c.issue_date, c.validity_date, 'academy/cert-rendered/SCHSH150067.png' FROM academy_certifications c WHERE c.id = 1 ON CONFLICT (user_id, certification_id) DO NOTHING;
INSERT INTO academy_coach_certifications (user_id, certification_id, earned_at, is_manual_issue, certificate_number, issue_date, expiry_date, cert_oss_key) SELECT '01255c93', 1, NOW(), TRUE, 'SCHCD021141', c.issue_date, c.validity_date, 'academy/cert-rendered/SCHCD021141.png' FROM academy_certifications c WHERE c.id = 1 ON CONFLICT (user_id, certification_id) DO NOTHING;
INSERT INTO academy_coach_certifications (user_id, certification_id, earned_at, is_manual_issue, certificate_number, issue_date, expiry_date, cert_oss_key) SELECT '0d5c3cd9', 1, NOW(), TRUE, 'SCHHZ240613', c.issue_date, c.validity_date, 'academy/cert-rendered/SCHHZ240613.png' FROM academy_certifications c WHERE c.id = 1 ON CONFLICT (user_id, certification_id) DO NOTHING;
INSERT INTO academy_coach_certifications (user_id, certification_id, earned_at, is_manual_issue, certificate_number, issue_date, expiry_date, cert_oss_key) SELECT '9e9998ea', 1, NOW(), TRUE, 'SCHPJ201040', c.issue_date, c.validity_date, 'academy/cert-rendered/SCHPJ201040.png' FROM academy_certifications c WHERE c.id = 1 ON CONFLICT (user_id, certification_id) DO NOTHING;
INSERT INTO academy_coach_certifications (user_id, certification_id, earned_at, is_manual_issue, certificate_number, issue_date, expiry_date, cert_oss_key) SELECT '45608991', 1, NOW(), TRUE, 'SCHSH252825', c.issue_date, c.validity_date, 'academy/cert-rendered/SCHSH252825.png' FROM academy_certifications c WHERE c.id = 1 ON CONFLICT (user_id, certification_id) DO NOTHING;
INSERT INTO academy_coach_certifications (user_id, certification_id, earned_at, is_manual_issue, certificate_number, issue_date, expiry_date, cert_oss_key) SELECT 'dc20b7f0', 1, NOW(), TRUE, 'SCHSZ27262X', c.issue_date, c.validity_date, 'academy/cert-rendered/SCHSZ27262X.png' FROM academy_certifications c WHERE c.id = 1 ON CONFLICT (user_id, certification_id) DO NOTHING;
INSERT INTO academy_coach_certifications (user_id, certification_id, earned_at, is_manual_issue, certificate_number, issue_date, expiry_date, cert_oss_key) SELECT 'ef5e5ff3', 1, NOW(), TRUE, 'SCHSH151524', c.issue_date, c.validity_date, 'academy/cert-rendered/SCHSH151524.png' FROM academy_certifications c WHERE c.id = 1 ON CONFLICT (user_id, certification_id) DO NOTHING;
INSERT INTO academy_coach_certifications (user_id, certification_id, earned_at, is_manual_issue, certificate_number, issue_date, expiry_date, cert_oss_key) SELECT '2f2cfeec', 1, NOW(), TRUE, 'SCHHZ094519', c.issue_date, c.validity_date, 'academy/cert-rendered/SCHHZ094519.png' FROM academy_certifications c WHERE c.id = 1 ON CONFLICT (user_id, certification_id) DO NOTHING;
INSERT INTO academy_coach_certifications (user_id, certification_id, earned_at, is_manual_issue, certificate_number, issue_date, expiry_date, cert_oss_key) SELECT '5258fefc', 1, NOW(), TRUE, 'SCHWH187011', c.issue_date, c.validity_date, 'academy/cert-rendered/SCHWH187011.png' FROM academy_certifications c WHERE c.id = 1 ON CONFLICT (user_id, certification_id) DO NOTHING;
INSERT INTO academy_coach_certifications (user_id, certification_id, earned_at, is_manual_issue, certificate_number, issue_date, expiry_date, cert_oss_key) SELECT '44b2292b', 1, NOW(), TRUE, 'SCHAS172124', c.issue_date, c.validity_date, 'academy/cert-rendered/SCHAS172124.png' FROM academy_certifications c WHERE c.id = 1 ON CONFLICT (user_id, certification_id) DO NOTHING;
