// Auto-generated by temp/upload-avatar-gallery.js — do not hand-edit.
// Regenerate by re-running that script if the gallery images change.

const MOODS = ["engaged","relaxed","restored","stressed"]

const AVATAR_GALLERY = [
  {
    "id": "avatar-01",
    "thumb": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-01-thumb.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457698&Signature=wRBXd9jFk1fn0oQFvAmuNBn%2FBgY%3D",
    "moods": {
      "engaged": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-01-engaged.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457698&Signature=ZCfdmN1hMnEe%2F%2Bfc6bmLlT%2B41a4%3D",
      "relaxed": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-01-relaxed.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457698&Signature=L0FQ2b8iNZxoWPGVs%2FmYF6Q1Zgk%3D",
      "restored": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-01-restored.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457698&Signature=n8Jjp31TmucrC81CcpcyLWdyApw%3D",
      "stressed": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-01-stressed.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457698&Signature=Qts6Vnr31LpZ%2B5ljGvRKobvmNmw%3D"
    }
  },
  {
    "id": "avatar-02",
    "thumb": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-02-thumb.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457698&Signature=ketBuooMr4Q3WFBCJhqxzTktjLM%3D",
    "moods": {
      "engaged": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-02-engaged.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457698&Signature=iKDRBrI3fRCPsOgr3PyY2Y%2Fvwic%3D",
      "relaxed": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-02-relaxed.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457698&Signature=ibGTfHISvhluufJmDQOTWrz4vUk%3D",
      "restored": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-02-restored.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457698&Signature=9ZoCoWMOmXmegydkqeYMKnsRrhI%3D",
      "stressed": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-02-stressed.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457698&Signature=A6zBtzF77RTd1Z6y%2Bdsi07dJFio%3D"
    }
  },
  {
    "id": "avatar-03",
    "thumb": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-03-thumb.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457699&Signature=IZqEMSNHKD%2B2CHgh6A%2BbBqXHpNI%3D",
    "moods": {
      "engaged": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-03-engaged.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457698&Signature=YZxAcT4nITfToFWtCrtuHjjvB%2Fo%3D",
      "relaxed": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-03-relaxed.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457698&Signature=pjYIxIctEMkLzwTjhgv1hKGIz%2Bo%3D",
      "restored": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-03-restored.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457699&Signature=pjgido0A9xpD46%2FdjDpLabMJSgQ%3D",
      "stressed": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-03-stressed.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457699&Signature=j6zD8sR1RoDphJm9P5sWHCEWtdM%3D"
    }
  },
  {
    "id": "avatar-04",
    "thumb": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-04-thumb.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457699&Signature=zLRa0zRiFu%2BjAcUISpl3WQsPM5U%3D",
    "moods": {
      "engaged": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-04-engaged.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457699&Signature=1rcpFJndFsy81o6CZR2oHHP53oU%3D",
      "relaxed": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-04-relaxed.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457699&Signature=rtiy1fk6233AW0MjHUWWqFAVoWc%3D",
      "restored": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-04-restored.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457699&Signature=Zzql71z4oAeO8WTyMh%2BFqkMcwwM%3D",
      "stressed": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-04-stressed.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457699&Signature=jaEr6Ldptbfxtvddunl%2BhhE9UJw%3D"
    }
  },
  {
    "id": "avatar-05",
    "thumb": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-05-thumb.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457699&Signature=rhvYeo64JDOYQhavqlJniKLLo6g%3D",
    "moods": {
      "engaged": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-05-engaged.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457699&Signature=sm1vPafwSAZKxmz9lDdca%2FQl8Mo%3D",
      "relaxed": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-05-relaxed.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457699&Signature=zt5lYBzIrhd9Dq3MjSXow0PcQB0%3D",
      "restored": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-05-restored.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457699&Signature=nLSnF2Nd6waeh3JLM77P%2FFwpKXU%3D",
      "stressed": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-05-stressed.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457699&Signature=hebTyUzTuZL3WTmaSzgSFTGAm04%3D"
    }
  },
  {
    "id": "avatar-06",
    "thumb": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-06-thumb.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457700&Signature=X1VtskxBzalY7slTO2WStTl2JQg%3D",
    "moods": {
      "engaged": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-06-engaged.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457699&Signature=N5moV3TnJZ7MPKWVl8Yd2jZizUM%3D",
      "relaxed": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-06-relaxed.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457700&Signature=5i1Lev5bZab9CSo1mOOp38zqiWg%3D",
      "restored": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-06-restored.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457700&Signature=v7McSnHLZFe23SgH%2FARBDlfggkU%3D",
      "stressed": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-06-stressed.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457700&Signature=lLCxy1tL5ZZynFb3YRpJRrDj%2F%2FU%3D"
    }
  },
  {
    "id": "avatar-07",
    "thumb": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-07-thumb.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457700&Signature=L0gqPaz1xPjVEpD2motWVitFDGI%3D",
    "moods": {
      "engaged": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-07-engaged.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457700&Signature=X4EP3iNsZpJ7pJmmgKmosBA2Udw%3D",
      "relaxed": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-07-relaxed.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457700&Signature=B1xCms%2F1R8A%2ByPC7D5QX1s0BRr4%3D",
      "restored": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-07-restored.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457700&Signature=2KlR0OPSwd%2BebaK2rRGxuLoRnoU%3D",
      "stressed": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-07-stressed.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457700&Signature=XMRCrKREwUsrerWUwupbJkMI4Yc%3D"
    }
  },
  {
    "id": "avatar-08",
    "thumb": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-08-thumb.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457700&Signature=tk40DQNdus4ViZXvf3dLOJ25tSI%3D",
    "moods": {
      "engaged": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-08-engaged.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457700&Signature=09eS4sZvJGG6o5Sqf%2BdKuix6nT4%3D",
      "relaxed": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-08-relaxed.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457700&Signature=pss8t0uC%2Fb%2FuoaJBKqTL5lPjJo8%3D",
      "restored": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-08-restored.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457700&Signature=4975pTwQor8OIxyj%2BLkfYO5LH5g%3D",
      "stressed": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-08-stressed.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457700&Signature=d0ShxDqw00BrY6k1gv1oLwjo7BE%3D"
    }
  },
  {
    "id": "avatar-09",
    "thumb": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-09-thumb.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457701&Signature=EXTEhjir4fxjM9bPRRxqnzthnQ4%3D",
    "moods": {
      "engaged": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-09-engaged.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457701&Signature=w48HxcbG89vUCHVZ6DOsixdCl0c%3D",
      "relaxed": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-09-relaxed.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457701&Signature=Qv8hrZ5chH2UB3QqJn9j4mGTO3k%3D",
      "restored": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-09-restored.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457701&Signature=6cvNAePc3YT7fosVw0U42uvsx2g%3D",
      "stressed": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-09-stressed.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457701&Signature=1GtwmFBpfR8ER6Y76vzD6QBKpYs%3D"
    }
  },
  {
    "id": "avatar-10",
    "thumb": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-10-thumb.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457701&Signature=ExOQCYlAuCkQHbQ0Hj92Kr0gXn4%3D",
    "moods": {
      "engaged": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-10-engaged.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457701&Signature=jC%2BpygdMMDRUYKxlhL6irtjVzqU%3D",
      "relaxed": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-10-relaxed.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457701&Signature=7aSEq7ToDJphL2yopmPE6IBZIFM%3D",
      "restored": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-10-restored.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457701&Signature=EmsUlOt2ybin3nKPIf8bzn4DPaE%3D",
      "stressed": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-10-stressed.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457701&Signature=HLdPElqmzo6pYdXkwSgP46TWVCw%3D"
    }
  },
  {
    "id": "avatar-11",
    "thumb": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-11-thumb.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457701&Signature=dQpJSYXwfTZ21%2FYpNlB9gAdBHCo%3D",
    "moods": {
      "engaged": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-11-engaged.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457701&Signature=YqyizX8tS6NR8Ofv1v1z4ZZQQN0%3D",
      "relaxed": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-11-relaxed.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457701&Signature=0cxcDC7vISxERVJAbThU52ExTvQ%3D",
      "restored": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-11-restored.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457701&Signature=%2Bxnn8cyDeUjlzLcaatUBZgGQIz0%3D",
      "stressed": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-11-stressed.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457701&Signature=lVe5MbSrpLct1XmwKAKl8kooRPY%3D"
    }
  },
  {
    "id": "avatar-12",
    "thumb": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-12-thumb.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457702&Signature=yv9vGZS8p1WpSSFp9KXbGn%2F39WI%3D",
    "moods": {
      "engaged": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-12-engaged.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457702&Signature=1e6fYESwTOAQGeHxYMT1nkFTWw8%3D",
      "relaxed": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-12-relaxed.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457702&Signature=fp99PwwmYL423lDjoDDTTVNOei8%3D",
      "restored": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-12-restored.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457702&Signature=9oa%2BvWQDlt516HJ4PFStd%2BOWHSg%3D",
      "stressed": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-12-stressed.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457702&Signature=JYDz1A%2BTYQ0ez%2Bk9TyQpsFqF31w%3D"
    }
  },
  {
    "id": "avatar-13",
    "thumb": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-13-thumb.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457702&Signature=n0CSFrA5rZxVIyRrU4O%2ByJhenyk%3D",
    "moods": {
      "engaged": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-13-engaged.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457702&Signature=OzALP6NcDhnC1GDEUEG5gnOkBZM%3D",
      "relaxed": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-13-relaxed.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457702&Signature=kWhGeNjia4f1iSvu%2BxFL%2FNcUl34%3D",
      "restored": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-13-restored.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457702&Signature=35bhqOTVG4tH9CYWeL2dhI4d0Gs%3D",
      "stressed": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-13-stressed.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457702&Signature=ouyEUpTJxArCkJrIOYS6JobKw2s%3D"
    }
  },
  {
    "id": "avatar-14",
    "thumb": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-14-thumb.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457702&Signature=XOmhFUdOzLEWzcwPRaqSuxLCCFM%3D",
    "moods": {
      "engaged": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-14-engaged.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457702&Signature=AkHHoCJc4AyoG1tKtXE8T6uyosg%3D",
      "relaxed": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-14-relaxed.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457702&Signature=7GLJ6RyNmHKOjgJbTGoe16yCAfA%3D",
      "restored": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-14-restored.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457702&Signature=O4BoTmzjTlT8Ky9h0bngGGxDjPk%3D",
      "stressed": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-14-stressed.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457702&Signature=ATqiURnefmUvwHma3C%2BJNdpZ5J4%3D"
    }
  },
  {
    "id": "avatar-15",
    "thumb": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-15-thumb.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457703&Signature=4hQfxb2VzEeXPhYRSZUCqr5qlzc%3D",
    "moods": {
      "engaged": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-15-engaged.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457703&Signature=ccBIYWSTVFpvVXSc1alPpiQleXo%3D",
      "relaxed": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-15-relaxed.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457703&Signature=gH61IU7%2FWG%2BFie%2BuwPwyjA0tj64%3D",
      "restored": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-15-restored.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457703&Signature=gkAoBDOIAO7FbjzLjJBrLde62Bc%3D",
      "stressed": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-15-stressed.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457703&Signature=nFQyC3AF08PcRuHn2TxOahYbq5Y%3D"
    }
  },
  {
    "id": "avatar-16",
    "thumb": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-16-thumb.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457703&Signature=OBPmf87rwWMshTxbjyzPplrP3Uw%3D",
    "moods": {
      "engaged": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-16-engaged.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457703&Signature=I0SETX%2BK7%2Bt%2BsazAz2%2FrxJtt7bI%3D",
      "relaxed": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-16-relaxed.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457703&Signature=LUxhRSB6649CuuqPtwpNq7OdhFA%3D",
      "restored": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-16-restored.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457703&Signature=g9qiv3I2GbwRVwK6Vvp%2FjLMjfq8%3D",
      "stressed": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-16-stressed.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457703&Signature=Ads9scnCAPK2gTMroE93nF7y1Yw%3D"
    }
  },
  {
    "id": "avatar-17",
    "thumb": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-17-thumb.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457704&Signature=QII569OJIkI53hN9rlSeZppyUuI%3D",
    "moods": {
      "engaged": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-17-engaged.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457703&Signature=wk6eLbwIV81ixE1MWv6p21XO%2B24%3D",
      "relaxed": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-17-relaxed.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457703&Signature=hPsDToGNMTSvTJ8MLoEXoEO%2BGwI%3D",
      "restored": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-17-restored.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457703&Signature=3Dd0U%2Brm9mtnB%2BrX6l93hgRhZzo%3D",
      "stressed": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-17-stressed.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457703&Signature=QZVB0HulfObiTM9z0Q%2F%2BxozNdls%3D"
    }
  },
  {
    "id": "avatar-18",
    "thumb": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-18-thumb.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457704&Signature=SkJHSMQ7w%2FKxY6glJtuYCvxWdbg%3D",
    "moods": {
      "engaged": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-18-engaged.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457704&Signature=bOF6OJuBuj10zhiYiJQKEe72BYg%3D",
      "relaxed": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-18-relaxed.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457704&Signature=K%2BrQ20bCvZRROLMMEoY4i5vAey4%3D",
      "restored": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-18-restored.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457704&Signature=KGudhGJExkvm%2BNA53kaHrsLyhOM%3D",
      "stressed": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-18-stressed.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457704&Signature=OeX4tRK0Wn%2BZcbZ4uXGGNHsUIdk%3D"
    }
  },
  {
    "id": "avatar-19",
    "thumb": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-19-thumb.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457704&Signature=CMYJOsjTdsDQnctxTw1HVIOYh2c%3D",
    "moods": {
      "engaged": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-19-engaged.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457704&Signature=%2BUnmjHlhmEqILVIx4qcAiwx21Uw%3D",
      "relaxed": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-19-relaxed.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457704&Signature=cXt6glatmBxu9tGlyXItTId8X80%3D",
      "restored": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-19-restored.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457704&Signature=%2FUPekKkI8vWoFlbX2yzvv4%2Fe1Sw%3D",
      "stressed": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-19-stressed.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457704&Signature=3CnOMb3zt7c2aP%2F62DSuYAVPycA%3D"
    }
  },
  {
    "id": "avatar-20",
    "thumb": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-20-thumb.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457704&Signature=cLigHMr7a1ABq%2F40pUBVScNBhjQ%3D",
    "moods": {
      "engaged": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-20-engaged.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457704&Signature=da8N%2Ft3g6cdIAoBocf5t5MeXon4%3D",
      "relaxed": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-20-relaxed.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457704&Signature=SsOKLwIVxhOMdHOZgldJq18keIo%3D",
      "restored": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-20-restored.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457704&Signature=9X%2FGUEkP4L9EpykH6o5UAFeM8Vg%3D",
      "stressed": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-20-stressed.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457704&Signature=kNauTIyQNz5QHJTEaI9BWIozohM%3D"
    }
  },
  {
    "id": "avatar-21",
    "thumb": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-21-thumb.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457705&Signature=m2BWMq0T1nVgwhu%2FuoB%2BZZie8w0%3D",
    "moods": {
      "engaged": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-21-engaged.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457705&Signature=KWEk2d2yPrKOmiEK8twPJaVPtHU%3D",
      "relaxed": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-21-relaxed.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457705&Signature=dxhDfz9V%2BUEMebG%2F4P%2F2nkOxJUw%3D",
      "restored": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-21-restored.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457705&Signature=EAudpdFKQ6ytKnDZIj6uunFDdqc%3D",
      "stressed": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-21-stressed.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457705&Signature=9IFGkg0bPAwaLgYPKe0H1fUivXE%3D"
    }
  },
  {
    "id": "avatar-22",
    "thumb": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-22-thumb.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457705&Signature=CTB9MUWOvK3C4FZSY2vPDSSuGzk%3D",
    "moods": {
      "engaged": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-22-engaged.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457705&Signature=yyaHY5Mj%2FuJ27370h%2BWQQ%2FYF110%3D",
      "relaxed": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-22-relaxed.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457705&Signature=SHpdeDftmtEePivGCvtbI26vFxY%3D",
      "restored": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-22-restored.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457705&Signature=uDItLoOefgHGFGyrPoCH2iaGZ8k%3D",
      "stressed": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-22-stressed.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457705&Signature=Ks8PCT0BzTkM%2FkZm5Pg%2FPxnpY%2FQ%3D"
    }
  },
  {
    "id": "avatar-23",
    "thumb": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-23-thumb.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457705&Signature=RMjdICmHVjifIb4nO0ATG23Mq0A%3D",
    "moods": {
      "engaged": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-23-engaged.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457705&Signature=At0i7fshuABNTR6w2IlOCWZmHws%3D",
      "relaxed": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-23-relaxed.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457705&Signature=%2FePPW%2FlGJHUaFZtN31PCXc%2B2Abk%3D",
      "restored": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-23-restored.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457705&Signature=Yg5%2Bq744QvLvidIehDmymITHhCo%3D",
      "stressed": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-23-stressed.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457705&Signature=EAxkgYVXNd36atnwJ7fjOLFeLe4%3D"
    }
  },
  {
    "id": "avatar-24",
    "thumb": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-24-thumb.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457706&Signature=lcYqJ%2FymW55QMMIOPADKdpOvSMs%3D",
    "moods": {
      "engaged": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-24-engaged.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457706&Signature=J1enqvPanIV6uGvL%2BPx2oXi5zTU%3D",
      "relaxed": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-24-relaxed.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457706&Signature=TZ8hW8JxL6Aly25UPWqP3qLVvBQ%3D",
      "restored": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-24-restored.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457706&Signature=fa1Si41shFyTiIoo7vmRP%2Fwbs4E%3D",
      "stressed": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-24-stressed.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457706&Signature=Fxoj98DqZq0EYOQeXAL3z%2B6eslA%3D"
    }
  },
  {
    "id": "avatar-25",
    "thumb": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-25-thumb.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457706&Signature=zB5qrxDCwR9bMmWqZGbcwSDokQM%3D",
    "moods": {
      "engaged": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-25-engaged.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457706&Signature=figTor3UBXGDsJffBh6dku2wJ%2Fk%3D",
      "relaxed": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-25-relaxed.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457706&Signature=WBw0jhIsDOMNnsctrXUQy%2BdXrR0%3D",
      "restored": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-25-restored.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457706&Signature=omBOx7L5YwLipKLmRFRiLp%2FdT68%3D",
      "stressed": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-25-stressed.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457706&Signature=53r3XzD1RnjtSMCDlwhU6wwRBR8%3D"
    }
  },
  {
    "id": "avatar-26",
    "thumb": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-26-thumb.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457706&Signature=WzoiyEVDmIn%2FUzGyUpqc%2FSMBW3I%3D",
    "moods": {
      "engaged": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-26-engaged.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457706&Signature=CuQi7gebwUP9dVZk%2BAcKgOT03W8%3D",
      "relaxed": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-26-relaxed.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457706&Signature=%2BCDsl1FIZK1%2F2aw3MPNpi9dMvSE%3D",
      "restored": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-26-restored.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457706&Signature=fIvbnqqKubcB9ExvgNzO2jPiah0%3D",
      "stressed": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-26-stressed.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457706&Signature=Z0ymAT%2F3FGlbBbcGtmJUvZ9APQE%3D"
    }
  },
  {
    "id": "avatar-27",
    "thumb": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-27-thumb.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457707&Signature=QWxJVw%2FFSd%2BmcPAy%2BENpM00rUJ0%3D",
    "moods": {
      "engaged": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-27-engaged.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457707&Signature=Reh%2FKQOelBxH5S4P3NHPiW70yyQ%3D",
      "relaxed": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-27-relaxed.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457707&Signature=eOQTiL%2B19BNSGE3ej%2FL8PFtU3sY%3D",
      "restored": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-27-restored.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457707&Signature=%2BstyiEqrusCWMI5ldIgfrWIwnkc%3D",
      "stressed": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-27-stressed.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457707&Signature=217dCiQDX7j7%2B2npiDlAMULFqV8%3D"
    }
  },
  {
    "id": "avatar-28",
    "thumb": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-28-thumb.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457707&Signature=c8p6XVchP4CyIDVTiE5pOZHb98g%3D",
    "moods": {
      "engaged": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-28-engaged.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457707&Signature=Yueq92WKj4Q2cWMJlPQo7U5%2FTbI%3D",
      "relaxed": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-28-relaxed.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457707&Signature=14ijMMflYJX5UBrL5V2kZDj4FcI%3D",
      "restored": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-28-restored.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457707&Signature=o9GCu7GgdpX14I60OBmEBene4xc%3D",
      "stressed": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-28-stressed.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457707&Signature=JUcbxE%2B6VsNouw%2B0wmxUHQAkSX0%3D"
    }
  },
  {
    "id": "avatar-29",
    "thumb": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-29-thumb.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457707&Signature=zJOZE1w1HRLeWiJKVAD3B6tf2FM%3D",
    "moods": {
      "engaged": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-29-engaged.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457707&Signature=rSqFXqs54ZtDpMFs1nMrx%2B%2Ftx%2BY%3D",
      "relaxed": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-29-relaxed.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457707&Signature=lAyNGS%2BwxVrD5A5Zku9mat5UMJw%3D",
      "restored": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-29-restored.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457707&Signature=m2LvJvsFdhIrd06fgWholvXOSoU%3D",
      "stressed": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-29-stressed.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457707&Signature=obQw8%2BQID8plVAfMlZu4PlFLUz0%3D"
    }
  },
  {
    "id": "avatar-30",
    "thumb": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-30-thumb.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457708&Signature=lcJBLRGN6gW3oZmwu9X7UMXTLnQ%3D",
    "moods": {
      "engaged": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-30-engaged.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457707&Signature=zgXZvBbJEY86PStW3hBHI7ANYZY%3D",
      "relaxed": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-30-relaxed.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457708&Signature=FQYB0hJH2pcDGzriqWjEavr%2FdZM%3D",
      "restored": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-30-restored.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457708&Signature=j7zbO1gVWc5Tu%2FduO6Le1ZIc4%2FA%3D",
      "stressed": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-30-stressed.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457708&Signature=dHedMZYiURQfhFgeNJ9ROAqBAFE%3D"
    }
  },
  {
    "id": "avatar-31",
    "thumb": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-31-thumb.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457708&Signature=avyJNRBqi2X9m32IuYXu3g6HGNw%3D",
    "moods": {
      "engaged": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-31-engaged.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457708&Signature=B2HBWfTzCM2mbj%2Fde80o39YCi%2Bw%3D",
      "relaxed": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-31-relaxed.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457708&Signature=D3cMcY5PKRKBXajUaV6I87nvXwE%3D",
      "restored": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-31-restored.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457708&Signature=EKKyVj80tgMAY0cm%2B3GEbwCWbz8%3D",
      "stressed": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-31-stressed.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457708&Signature=qV8SPsEJD7RDt8e6rrZHF%2BXT21c%3D"
    }
  },
  {
    "id": "avatar-32",
    "thumb": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-32-thumb.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457708&Signature=IM9nkTfNBJ4PGNbyhcBHjEOnJDo%3D",
    "moods": {
      "engaged": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-32-engaged.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457708&Signature=og1Jw6kTO8pX%2F24mOvTWKhO1q4M%3D",
      "relaxed": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-32-relaxed.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457708&Signature=x83ijnOwjcBiG7k10rNttVM9hzA%3D",
      "restored": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-32-restored.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457708&Signature=oTYq9X8JN9DSJxO8dWv5evctJD4%3D",
      "stressed": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-32-stressed.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457708&Signature=QGFlOLJvTrvQZqvpl6dHgfuzIwA%3D"
    }
  },
  {
    "id": "avatar-33",
    "thumb": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-33-thumb.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457709&Signature=Bnl%2F5M2dsxQZ44e4I3jQFbSQFS4%3D",
    "moods": {
      "engaged": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-33-engaged.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457708&Signature=qOUJ%2BIW%2BGQZ32ootzP5CA9djEyM%3D",
      "relaxed": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-33-relaxed.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457709&Signature=jAwQ1eT%2FazYUzrt8mLvlnmY9eDE%3D",
      "restored": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-33-restored.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457709&Signature=M893TKrGT5GPug2aXIsKSlUS4tc%3D",
      "stressed": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-33-stressed.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457709&Signature=we0DtKW9RQzXv1g66tjtaIRavrY%3D"
    }
  },
  {
    "id": "avatar-34",
    "thumb": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-34-thumb.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457709&Signature=YxjzVqt320eqXz4KVP%2FU%2FBwNsvk%3D",
    "moods": {
      "engaged": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-34-engaged.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457709&Signature=oofCuWaJqiWXuW0ArNBiipNxh3U%3D",
      "relaxed": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-34-relaxed.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457709&Signature=jw%2FdVbgxaKZZGxhmERwPW8%2BKJ8o%3D",
      "restored": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-34-restored.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457709&Signature=ryNy0zUe2w1CNoWvbqCMcIClE0I%3D",
      "stressed": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-34-stressed.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457709&Signature=xMGJkCXZ0V47%2BTFS3iHTrZfLOlI%3D"
    }
  },
  {
    "id": "avatar-35",
    "thumb": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-35-thumb.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457709&Signature=KyyuThmItyVtZxgtsF5G3%2BMTPf8%3D",
    "moods": {
      "engaged": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-35-engaged.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457709&Signature=GBsiwIHokmva55LTtD0PrxFCw8Q%3D",
      "relaxed": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-35-relaxed.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457709&Signature=b9CdodYNq5Ei9nXb3bhvug2iP6M%3D",
      "restored": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-35-restored.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457709&Signature=J0UeKqXZrdOOQ3iG0NdOTrurfGs%3D",
      "stressed": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-35-stressed.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457709&Signature=cR9yuJijy4T3%2B58kfpohXLJA91M%3D"
    }
  },
  {
    "id": "avatar-36",
    "thumb": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-36-thumb.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457709&Signature=nI45e2wS95hTGti0gNy5PRPN%2FM8%3D",
    "moods": {
      "engaged": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-36-engaged.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457709&Signature=5dTRMHym82vqq9LfhMKR21Sx4VQ%3D",
      "relaxed": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-36-relaxed.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457709&Signature=mHh68l0AjuCXz1qRU3q1Qa2wRWE%3D",
      "restored": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-36-restored.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457709&Signature=OV%2BnTvhbIAFchO2ey0KGdJUvrMk%3D",
      "stressed": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-36-stressed.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457709&Signature=MJMmzx5BkPTrzakyFq1zpT1sh9A%3D"
    }
  },
  {
    "id": "avatar-37",
    "thumb": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-37-thumb.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457710&Signature=UiZNh6sFeg9SvVnItSDoD6MtL%2F4%3D",
    "moods": {
      "engaged": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-37-engaged.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457709&Signature=c%2Bcs0vPHneksNSIG77xXMLEtgOc%3D",
      "relaxed": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-37-relaxed.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457710&Signature=6KC56HCCQn9MSN3pHXJhpzzScqo%3D",
      "restored": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-37-restored.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457710&Signature=ABkXodZiO0UI3h4782LNVZ9hHAo%3D",
      "stressed": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-37-stressed.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457710&Signature=mcUnWGBdC8Q%2F2kc%2BT2yOBEBgqtU%3D"
    }
  },
  {
    "id": "avatar-38",
    "thumb": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-38-thumb.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457710&Signature=hmvrXD8Gm4y6eLGk91qcNGtiBOE%3D",
    "moods": {
      "engaged": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-38-engaged.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457710&Signature=aMKBwIhfm4TACfyCHZ9UOe8ko0w%3D",
      "relaxed": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-38-relaxed.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457710&Signature=o7M29PM4dvgs8bUOIqtoxqFt9fM%3D",
      "restored": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-38-restored.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457710&Signature=9Dl3cap1uYMYG8bXb8Xt82JkFxo%3D",
      "stressed": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-38-stressed.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457710&Signature=LzTxwjCl%2B71Z80eMKJvM0jqA88g%3D"
    }
  },
  {
    "id": "avatar-39",
    "thumb": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-39-thumb.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457710&Signature=OeEZyCaZpf0uPbGUR76vdwDg1Rk%3D",
    "moods": {
      "engaged": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-39-engaged.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457710&Signature=8JxT7NqipWjUUE6HA4jod9Vu7aA%3D",
      "relaxed": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-39-relaxed.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457710&Signature=SVy%2By3zz5Pai3x2SnN4ybrxo70g%3D",
      "restored": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-39-restored.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457710&Signature=Oh%2FJbp1lsEiAubHa%2BKtydhrWAKE%3D",
      "stressed": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-39-stressed.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457710&Signature=FYFfHUAEiyzDB9ZW8MKsgEBe%2BGM%3D"
    }
  },
  {
    "id": "avatar-40",
    "thumb": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-40-thumb.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457710&Signature=uvJgRYOc8rejTLxE%2FeEgwL9NyIE%3D",
    "moods": {
      "engaged": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-40-engaged.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457710&Signature=BoTHvOAif6LjW1NsJdscuMDFD%2Fg%3D",
      "relaxed": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-40-relaxed.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457710&Signature=f0jKYI%2BmNzp1YHZ0Zs5Y4nT2opA%3D",
      "restored": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-40-restored.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457710&Signature=JdPL1EK2mUfgeI%2FH3SJOSf%2F60Bc%3D",
      "stressed": "https://waven-nano.oss-cn-shanghai.aliyuncs.com/avatars/gallery/avatar-40-stressed.jpg?OSSAccessKeyId=LTAI5t6bJNW5XQyeiNr2MUp4&Expires=2100457710&Signature=peyhpiLX%2B%2Br9R0z4TxTqWmNLsf0%3D"
    }
  }
]

module.exports = { MOODS, AVATAR_GALLERY }
